### ISSUE TITLE
Syntax Error: unexpected tLABEL

### ISSUE THREAD

**Issue by okashino** [stevenosloan/slack-notifier#70]
Getting the following error when trying to load the gem:
``
/gems_path/.gem/ruby/1.9.1/gems/slack-notifier-2.1.0/lib/slack-notifier.rb:6:in `require_relative': /gems_path/.gem/ruby/1.9.1/gems/slack-notifier-2.1.0/lib/slack-notifier/util/link_formatter.rb:20: syntax error, unexpected tLABEL (SyntaxError)
        def initialize string, formats: [:html, :markdown]
                                       ^
/gems_path/.gem/ruby/1.9.1/gems/slack-notifier-2.1.0/lib/slack-notifier/util/link_formatter.rb:63: syntax error, unexpected keyword_end, expecting $end
        from /gems_path/.gem/ruby/1.9.1/gems/slack-notifier-2.1.0/lib/slack-notifier.rb:6:in `<top (required)>'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /gems_path/.gem/ruby/1.9.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from build.rb:3:in `<main>'
``
I'm running Ruby version 1.9.3p551

**Comment by stevenosloan** [comment]
As of 2.0 support for ruby 1.9.3 was dropped so I could use keyword arguments ([1.9.3 has been EOL for more than two years](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)).

If you drop back to 1.5.1 you should be fine, but check [it's readme](https://github.com/stevenosloan/slack-notifier/blob/6e6a4df20b9ec8680d9ee1dcf7cb6f0b6d511dbd/readme.md) since the call signature has change a little bit. Sorry the change there wasn't better called out in the changelog, I took *way* to long for 2.0 and forgot a few things 😁

**Comment by okashino** [comment]
Thanks for the clarification! I agree with you that the readme/changelog should be updated with this information.
